source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SlidingTabbarController_Example', :exclusive => true do
  pod 'SlidingTabbarController', :path => '../'
end

target 'SlidingTabbarController_Tests', :exclusive => true do
  pod 'SlidingTabbarController', :path => '../'

  
end
